"""initial_schema

Revision ID: 051cc28df235
Revises: 
Create Date: 2026-04-08 20:50:23.519777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '051cc28df235'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_splits', 'expense_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('expense_splits', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('expense_splits', 'is_settled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('expense_splits_user_id_fkey', 'expense_splits', type_='foreignkey')
    op.create_foreign_key(None, 'expense_splits', 'users', ['user_id'], ['id'])
    op.alter_column('expenses', 'trip_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('expenses', 'paid_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('expenses', 'amount_base',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('expenses', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('expenses', 'category',
               existing_type=postgresql.ENUM('food', 'transport', 'accommodation', 'activities', 'other', name='expense_category'),
               nullable=False,
               existing_server_default=sa.text("'other'::expense_category"))
    op.alter_column('expenses', 'split_type',
               existing_type=postgresql.ENUM('equal', 'exact', 'percentage', 'shares', name='split_type'),
               nullable=False,
               existing_server_default=sa.text("'equal'::split_type"))
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('expenses_paid_by_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['paid_by'], ['id'])
    op.alter_column('notes', 'trip_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notes', 'author_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('notes_author_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['author_id'], ['id'])
    op.alter_column('settlements', 'trip_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('settlements', 'from_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('settlements', 'to_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('settlements', 'method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('settlements', 'is_partial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('settlements', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('settlements_from_user_id_fkey', 'settlements', type_='foreignkey')
    op.drop_constraint('settlements_to_user_id_fkey', 'settlements', type_='foreignkey')
    op.create_foreign_key(None, 'settlements', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'users', ['to_user_id'], ['id'])
    op.alter_column('trip_members', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trip_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'is_settled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trips', 'created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('trips_created_by_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['created_by'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'default_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'default_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_created_by_fkey', 'trips', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'created_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('trips', 'is_settled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('trip_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_members', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.create_foreign_key('settlements_to_user_id_fkey', 'settlements', 'users', ['to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('settlements_from_user_id_fkey', 'settlements', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('settlements', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('settlements', 'is_partial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('settlements', 'method',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('settlements', 'to_user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('settlements', 'from_user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('settlements', 'trip_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_author_id_fkey', 'notes', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('notes', 'author_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('notes', 'trip_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_paid_by_fkey', 'expenses', 'users', ['paid_by'], ['id'], ondelete='SET NULL')
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'split_type',
               existing_type=postgresql.ENUM('equal', 'exact', 'percentage', 'shares', name='split_type'),
               nullable=True,
               existing_server_default=sa.text("'equal'::split_type"))
    op.alter_column('expenses', 'category',
               existing_type=postgresql.ENUM('food', 'transport', 'accommodation', 'activities', 'other', name='expense_category'),
               nullable=True,
               existing_server_default=sa.text("'other'::expense_category"))
    op.alter_column('expenses', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('expenses', 'amount_base',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('expenses', 'paid_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expenses', 'trip_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'expense_splits', type_='foreignkey')
    op.create_foreign_key('expense_splits_user_id_fkey', 'expense_splits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('expense_splits', 'is_settled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('expense_splits', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expense_splits', 'expense_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
